
varnish:
  shortName: "semanticReaderVarnish"
  path: content/
  timeout: 4000ms
  connectionTimeout: 1s
  primaryNodes: "localhost:9090:9091"

pipeline:
  webUrlTemplates:
    "http://www.ft.com/ontology/origin/FTComMethode" : "https://www.ft.com/content/{{identifierValue}}"
    "http://www.ft.com/ontology/origin/FT-CLAMO"  : "https://www.ft.com/fastft?post={{identifierValue}}"
    "http://www.ft.com/ontology/origin/FT-LABS-WP-1-24" : "{{identifierValue}}"
    "http://www.ft.com/ontology/origin/FT-LABS-WP-1-91" : "{{identifierValue}}"
    "http://api.ft.com/system/FTCOM-METHODE" : "https://www.ft.com/content/{{identifierValue}}"
    "http://api.ft.com/system/FT-CLAMO"  : "https://www.ft.com/fastft?post={{identifierValue}}"
    "http://api.ft.com/system/FT-LABS-WP-1-[0-9]+" : "{{identifierValue}}"
    "http://api.ft.com/system/NEXT-VIDEO-EDITOR" : "https://www.ft.com/content/{{identifierValue}}"

policyBrandsMapper:
  policyFilterParameterList:
       - policy: FASTFT_CONTENT_ONLY
         forBrand:
                  - http://api.ft.com/things/5c7592a8-1f0c-11e4-b0cb-b2227cce2b54
       - policy: EXCLUDE_FASTFT_CONTENT
         notForBrand:
                  - http://api.ft.com/things/5c7592a8-1f0c-11e4-b0cb-b2227cce2b54

server:
  applicationConnectors:
      - type: http
        port: 20080
  adminConnectors:
      - type: http
        port: 20082
  requestLog:
    appenders: []
    type: external

logging:
  type: external
  level: INFO
  loggers:
    io.dropwizard: WARN
    io.dropwizard.jersey: "OFF"
    io.dropwizard.lifecycle: "OFF"
    io.dropwizard.servlets: "OFF"
    com.ft.platform.dropwizard.HealthCheckPageData: "OFF"
    com.ft.platform.dropwizard.metrics: "OFF"
    com.ft.platform.dropwizard: WARN
    org.eclipse.jetty: "OFF"
    org.glassfish.jersey.client: "OFF"
    sun.net.www.protocol.http: "OFF"
    com.ft.api.util.transactionid: INFO
    com.ft.api.util.buildinfo: "OFF"
    com.ft.bodyprocessing: WARN
    #    Switch the two below to INFO instead of "OFF" if you want to see stack traces NOT in JSON format
    com.ft.api.jaxrs.errors: "OFF"
    com.ft.api.jaxrs: WARN
  appenders:
    - type: console
      logFormat: "%m%n"

appInfo:
    systemCode: "APIPolicyComponent"
    description: "ApiPolicyApplication"

canonicalWebUrlTemplate: "https://www.ft.com/content/%s"
