# Default values for api-policy-component.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
service:
  name: "" # The name of the service, should be defined in the specific app-configs folder.
  hasHealthcheck: "true"
eksCluster: false
replicaCount: 2
image:
  repository: coco/api-policy-component
  pullPolicy: IfNotPresent
resources:
  requests:
    memory: 512Mi
    cpu: "450m"
  limits:
    memory: 1.3Gi
